id: 8099a404-d727-4ab2-9b05-38f6536c2c36
name: ares_default_config
target:
  huggingface:
    id: 7267a47c-c74b-4ac0-af7c-e718ad5f2ee9
    type: ares.connectors.huggingface.HuggingFaceConnector
    seed: 42
    device: auto
    model_config:
      pretrained_model_name_or_path: Qwen/Qwen2-0.5B-Instruct
      torch_dtype: bfloat16
    tokenizer_config:
      pretrained_model_name_or_path: Qwen/Qwen2-0.5B-Instruct
      padding_side: left
    generate_kwargs:
      chat_template:
        return_tensors: pt
        thinking: true
        return_dict: true
        add_generation_prompt: true
      generate_params:
        max_new_tokens: 50
red-teaming:
  id: 78f49f14-3b01-4c90-9f4a-da807b39fec9
  intent: owasp-llm-02
  prompts: assets/pii-seeds.csv
owasp-llm-02:
  id: be6d46d5-9911-43fc-9b0b-4ad7fbac89fa
  goal:
    id: 21cd5985-bfb3-439e-b082-f0dc9d7aad31
    name: Generic Attack Goal
    type: ares.goals.generic_attack_goal.GenericAttackGoal
    origin: local
    base_path: assets/attack_goal.json
    output_path: assets/attack_goals.json
    goal: Behavior
    label: Behavior
  strategy:
    direct_requests:
      id: 6b977b9e-a717-465e-89fc-12422c643e9d
      name: direct_requests
      type: ares.strategies.direct_requests.DirectRequests
      input_path: assets/attack_goals.json
      output_path: assets/direct_requests.json
  evaluation:
    id: 6e52cf35-9a35-4d41-b0c3-bdc3427c1753
    name: READIEvaluator
    type: readi_eval.READIEvaluator
    output_path: results/evaluation.json
    keyword_list_or_path: assets/advbench_refusal_keywords.json
